# GitHub Actions Integration Templates

# Template 1: Basic CI/CD Pipeline
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run linter
        run: npm run lint

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run security audit
        run: npm audit

      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy:
    needs: [test, lint, security]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to production
        run: npm run deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

---

# Template 2: Claude Workflow Pro Integration
name: Claude Workflow Automation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Auto Review PR
        run: |
          # Install Claude CLI
          npm install -g @claude/workflow-pro

          # Run auto-review
          claude /github/auto-review ${{ github.event.pull_request.number }}

      - name: Post Review Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('claude-review.md', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });

  auto-triage:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Auto Triage Issue
        run: |
          claude /github/auto-triage ${{ github.event.issue.number }} --apply

---

# Template 3: Automated Release
name: Automated Release

on:
  push:
    branches: [main]

jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version
        id: version
        run: |
          VERSION=$(claude /github/auto-release --detect-only)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        run: |
          claude /github/auto-release ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Team
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Released ${{ steps.version.outputs.version }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

---

# Template 4: Scheduled Metrics Report
name: Weekly Metrics

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Metrics Report
        run: |
          claude /agents/metrics "Generate team productivity report for last week"

      - name: Post to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: 'Weekly Metrics Report',
              attachments: [{
                text: fs.readFileSync('metrics-report.md', 'utf8')
              }]
            }
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
