name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
        3. Expected '...' but got '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: command
    attributes:
      label: Which command(s) are affected?
      multiple: true
      options:
        - "/workflow/init"
        - "/workflow/create-plan"
        - "/workflow/implement-plan"
        - "/workflow/validate-plan"
        - "/workflow/checkpoint"
        - "/workflow/resume-work"
        - "/github/setup-github-issues"
        - "/github/start-from-issue"
        - "/github/create-issue"
        - "/github/next-task"
        - "/github/describe-pr"
        - "/development/commit"
        - "/development/debug"
        - "/development/local-review"
        - "/research/research-codebase"
        - "Agent system"
        - "Configuration"
        - "Other"
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Claude Code Version
      description: What version of Claude Code are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of Claude Workflow Pro are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration from .claude-plugin-config.json (if any)
      placeholder: |
        {
          "directories": {...},
          "github": {...}
        }
      render: json

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      placeholder: Paste error messages here...
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any other information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I can reproduce this issue consistently
          required: false
