name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - "Workflow Management"
        - "GitHub Integration"
        - "Development Tools"
        - "Research/Analysis"
        - "Agent System"
        - "Configuration"
        - "Documentation"
        - "Testing"
        - "Performance"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - "New command"
        - "New agent"
        - "Enhancement to existing command"
        - "Enhancement to existing agent"
        - "Configuration option"
        - "Integration with external tool"
        - "Documentation improvement"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also considered...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        # Example usage
        /new-command --option value
      render: bash

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would be helpful"
        - "Important for my workflow"
        - "Critical / Blocking"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: Any other information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false
        - label: I am willing to test this feature when available
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and PRs to ensure this is not a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true
